### ISSUE TITLE
$50 bounty to the guy/guys who will implement this feature

### ISSUE THREAD

**Issue by 0xspade** [elkokc/reflector#22]
Hi,

Since reflector is just detecting characters like `' " > < /`, etc. I am thinking an injection like `%3E` then the server will detect `<` (although sometimes the server always convert this automatically, then there should be an option).

and also if the reflector injects `%253E` it will detect if the server decodes it as `<`.
`&lt;` as `<`
`\u003e` as `<`
`\x3e` as `<`
`＜` as `<`

take note that not only the different encodings of `<` should be implemented, the others should too. :)

**Comment by shelld3v** [comment]
Has this feature been implemented? Is the bounty still up for people?

**Comment by 0xspade** [comment]
> Has this feature been implemented? Is the bounty still up for people?

yep, this request is still open
