### ISSUE TITLE
javac compile errors

### ISSUE THREAD

**Issue by mahmoud0x01** [elkokc/reflector#9]
when compile with `javac` on linux machine with command `javac -source 1.8 -d ../build/ *.java`
it returns a lot of 
`
ender.java:476: error: method does not override or implement a method from a supertype
    @Override
    ^
BurpExtender.java:482: error: method does not override or implement a method from a supertype
    @Override
    ^
BurpExtender.java:488: error: method does not override or implement a method from a supertype
    @Override
    ^
BurpExtender.java:494: error: method does not override or implement a method from a supertype
    @Override
    ^
BurpExtender.java:500: error: method does not override or implement a method from a supertype
    @Override
    ^
CheckReflection.java:263: error: cannot find symbol
        if(parameter.get(TYPE) ==  IParameter.PARAM_JSON ){
                                   ^
  symbol:   variable IParameter
  location: class Aggressive
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
59 errors
`

**Comment by elkokc** [comment]
Hello!
Please, use jdk 1.7.
